//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBTI.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBTI.Resources.Properties.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Descriptions {
            get {
                object obj = ResourceManager.GetObject("Descriptions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Questions {
            get {
                object obj = ResourceManager.GetObject("Questions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrovert.
        /// </summary>
        public static string SExtrovert {
            get {
                return ResourceManager.GetString("SExtrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeling.
        /// </summary>
        public static string SFeeling {
            get {
                return ResourceManager.GetString("SFeeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to home screen.
        /// </summary>
        public static string SHomeTooltip {
            get {
                return ResourceManager.GetString("SHomeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the sentence that best describes you.
        /// </summary>
        public static string SInstruction1 {
            get {
                return ResourceManager.GetString("SInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be true to yourself.
        /// </summary>
        public static string SInstruction2 {
            get {
                return ResourceManager.GetString("SInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the quiz.
        /// </summary>
        public static string SInstruction3 {
            get {
                return ResourceManager.GetString("SInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personality type is.
        /// </summary>
        public static string SInstruction4 {
            get {
                return ResourceManager.GetString("SInstruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introvert.
        /// </summary>
        public static string SIntrovert {
            get {
                return ResourceManager.GetString("SIntrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuition.
        /// </summary>
        public static string SIntuition {
            get {
                return ResourceManager.GetString("SIntuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judging.
        /// </summary>
        public static string SJudging {
            get {
                return ResourceManager.GetString("SJudging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Myers–Briggs Type Indicator (MBTI) is a pseudoscientific introspective self-report questionnaire indicating differing psychological preferences in how people perceive the world and make decisions..
        /// </summary>
        public static string SMBTIDescription {
            get {
                return ResourceManager.GetString("SMBTIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perceptive.
        /// </summary>
        public static string SPerceptive {
            get {
                return ResourceManager.GetString("SPerceptive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality.
        /// </summary>
        public static string SPersonality {
            get {
                return ResourceManager.GetString("SPersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string SQuestion {
            get {
                return ResourceManager.GetString("SQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take a quiz.
        /// </summary>
        public static string SQuiz {
            get {
                return ResourceManager.GetString("SQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensing.
        /// </summary>
        public static string SSensing {
            get {
                return ResourceManager.GetString("SSensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn.
        /// </summary>
        public static string SStudy {
            get {
                return ResourceManager.GetString("SStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understands &amp; Helps you choose suitable jobs.
        /// </summary>
        public static string SSubtitle {
            get {
                return ResourceManager.GetString("SSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested jobs.
        /// </summary>
        public static string SSuggestedJobs {
            get {
                return ResourceManager.GetString("SSuggestedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking.
        /// </summary>
        public static string SThinking {
            get {
                return ResourceManager.GetString("SThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBTI.
        /// </summary>
        public static string STitle {
            get {
                return ResourceManager.GetString("STitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBTI.
        /// </summary>
        public static string STitleNormal {
            get {
                return ResourceManager.GetString("STitleNormal", resourceCulture);
            }
        }
    }
}
